name: demo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  fluttertoast: ^8.2.6
  shared_preferences: ^2.3.0
  device_info_plus: ^10.1.1
  android_id: ^0.4.0
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.2.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  intl: ^0.19.0
  pull_to_refresh: ^2.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  google_maps_flutter: ^2.9.0
  flutter_polyline_points: ^2.1.0
  flutter_local_notifications: ^17.2.2
  timeago: ^3.7.0
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  permission_handler: ^11.3.1
  uuid: ^4.5.1
  google_fonts: ^6.1.0
  url_launcher: ^6.3.1
  animated: ^2.0.0
  supabase_flutter: ^2.3.4
  path_provider: ^2.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  geocoding: ^4.0.0
  get_storage: ^2.1.1
  image_preview: ^1.3.19
  flutter_image_compress: ^2.4.0
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Splash_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/Splash_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/Splash_logo.png
    - assets/images/
    - assets/svg/